services:
  web:
    image: ghcr.io/tpoderoso/tools.poderoso.io:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    env_file:
      - .env
    restart: unless-stopped
